server:
  port: 8000

spring:
  application:
    name: gateway-server

  profiles:
    include:
    - route
    - jwt

# log level setting
logging:
  level:
    root: info
    com.ssafy: debug
    org.springframework.cloud.gateway: debug
    reactor.netty.http.client: debug
