spring:
  application:
    name: books-service

  profiles:
    include: db

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB