server:
  port: 8090

spring:
  application:
    name: auth-server

  # application-oauth
  profiles:
    include:
    - oauth
    - db

# log level setting
logging:
  level:
    root: info
    com:
      ssafy: debug

feign:
  hystrix:
    enabled: true