server:
  port: 9031

spring:
  application:
    name: books-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/girin

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB